'use client';
import {useEffect,useState} from 'react';
import {eventConfig as e} from '@/config/eventConfig';
type Row={id:string;guest_name:string;attendance:boolean;guest_count:number;message:string;dietary_restrictions:string;created_at:string};
export default function Admin({authenticated}:{authenticated:boolean}){const [logged,setLogged]=useState(authenticated);const [rows,setRows]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [loaded,setLoaded]=useState(false);
async function load(){setBusy(true);setError('');try{const res=await fetch('/api/admin/rsvp',{cache:'no-store'});const data=await res.json();if(!res.ok){if(res.status===401)setLogged(false);throw new Error(data.error)}setRows(data.rows);setLoaded(true)}catch(err){setError(err instanceof Error?err.message:'Error de conexión.')}finally{setBusy(false)}}
useEffect(()=>{if(logged)void load()},[logged]);
async function login(ev:React.FormEvent<HTMLFormElement>){ev.preventDefault();setBusy(true);setError('');const form=new FormData(ev.currentTarget);try{const res=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password')})});const data=await res.json();if(!res.ok)throw new Error(data.error);setLogged(true)}catch(err){setError(err instanceof Error?err.message:'Error de conexión.')}finally{setBusy(false)}}
async function logout(){setBusy(true);try{const res=await fetch('/api/admin/session',{method:'DELETE'});if(!res.ok)throw new Error('No se pudo cerrar sesión.');setLogged(false);setRows([]);setLoaded(false)}catch(err){setError(err instanceof Error?err.message:'Error de conexión.')}finally{setBusy(false)}}
function exportCsv(){const escape=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv=[['Nombre','Asiste','Personas','Acompañantes','Mensaje','Restricciones','Fecha'],...rows.map(r=>[r.guest_name,r.attendance?'Sí':'No',r.guest_count,Math.max(0,r.guest_count-1),r.message,r.dietary_restrictions,r.created_at])].map(r=>r.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='confirmaciones.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
return <main className="admin-page">{!logged?<div className="admin-login"><p className="eyebrow">{e.eventName} / Acceso privado</p><h1>Bienvenidos,<br/><em>anfitriones.</em></h1><form onSubmit={login}><label className="field">Correo electrónico<input name="email" type="email" autoComplete="username" required/></label><label className="field">Contraseña<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="submit-button" disabled={busy}>{busy?'Ingresando…':'Entrar'}</button></form><a href="/" className="text-link">Volver a la invitación</a></div>:<><div className="admin-top"><div><p className="eyebrow">{e.eventName} / Panel privado</p><h1>Lista de <em>invitados.</em></h1></div><button className="text-link" disabled={busy} onClick={logout}>Cerrar sesión</button></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="admin-stats">{[['Confirmaciones',rows.length],['Asistirán',rows.filter(r=>r.attendance).length],['No asistirán',rows.filter(r=>!r.attendance).length],['Personas confirmadas',rows.reduce((s,r)=>s+(r.attendance?r.guest_count:0),0)]].map(([label,value])=><div key={label}><strong>{loaded?value:'—'}</strong><span>{label}</span></div>)}</div><div className="admin-top"><button className="text-link" onClick={load} disabled={busy}>{busy?'Cargando…':'Actualizar listado'}</button><button className="text-link" onClick={exportCsv} disabled={!rows.length}>Exportar CSV</button></div>{loaded&&!rows.length?<p className="admin-empty">Aún no hay confirmaciones. Las respuestas aparecerán aquí.</p>:<div className="table-wrap"><table className="admin-table"><thead><tr>{['Nombre','Asistirá','Personas','Acompañantes','Mensaje','Restricciones','Confirmación'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.guest_name}</td><td>{r.attendance?'Sí':'No'}</td><td>{r.guest_count}</td><td>{Math.max(0,r.guest_count-1)}</td><td>{r.message||'—'}</td><td>{r.dietary_restrictions||'—'}</td><td>{new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:e.timeZone}).format(new Date(r.created_at))}</td></tr>)}</tbody></table></div>}</>}</main>}
