'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { motion, useReducedMotion, useScroll, useTransform } from 'motion/react';
import { ArrowDown, ArrowUpRight, CalendarDays, Volume2, VolumeX, Mail, MapPin } from 'lucide-react';
import { eventConfig as e } from '@/config/eventConfig';
import { eventStart, dateLabel } from '@/lib/event';

function Reveal({children,className=''}:{children:React.ReactNode;className?:string}) {const reduced=useReducedMotion();return <motion.div className={className} initial={{opacity:0,y:reduced?0:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:reduced?0:.9,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Label({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function Rule(){return <span className="fine-rule" aria-hidden="true"/>}
function Timeline(){const target=useRef<HTMLDivElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target,offset:['start 85%','end 60%']});return <div ref={target} className="timeline"><motion.span className="timeline-progress" style={{scaleY:reduced?1:scrollYProgress}}/>{e.timeline.map((item,i)=><div className="timeline-row" key={`${item.time}-${i}`}><time>{item.time}</time><span className="timeline-dot"/><div><h3>{item.title}</h3><p>{item.place}</p></div></div>)}</div>}
function Countdown(){const [remaining,setRemaining]=useState<number|null>(null);useEffect(()=>{const tick=()=>setRemaining(Math.max(0,eventStart().getTime()-Date.now()));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);const values=remaining===null?['—','—','—','—']:[Math.floor(remaining/86400000),Math.floor(remaining/3600000)%24,Math.floor(remaining/60000)%60,Math.floor(remaining/1000)%60].map(n=>String(n).padStart(2,'0'));return <section className="countdown dark"><Reveal><Label>{remaining===0?'Llegó el gran día':'Falta poco'}</Label><div className="count-grid" aria-label="Cuenta regresiva">{values.map((value,i)=><div key={i}><span className="count-number">{value}</span><span className="count-label">{['Días','Horas','Minutos','Segundos'][i]}</span></div>)}</div><p className="quiet">Para una noche que será inolvidable.</p></Reveal></section>}
function LocationLink({url,children}:{url:string;children:React.ReactNode}){return url?<a className="text-link" href={url} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16}/></a>:<div className="pending-location"><button className="text-link" disabled>{children}<ArrowUpRight size={16}/></button><span>Ubicación próximamente</span></div>}
function VenueMap({name,embedUrl}:{name:string;embedUrl:string}){return <div className="venue-map">{embedUrl?<iframe title={`Mapa: ${name}`} src={embedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/>:<div className="map-pending"><MapPin size={26} strokeWidth={1}/><p>{name}</p><span>El mapa estará disponible próximamente</span></div>}</div>}
function WhatsAppConfirmation(){
function confirm(event:React.FormEvent<HTMLFormElement>){
event.preventDefault();
const form=event.currentTarget;
const data=new FormData(form);
const name=String(data.get('family')||'').trim();
const count=Number(data.get('people'));
if(!name||!Number.isSafeInteger(count)||count<1)return;
const message=`¡Hola! Confirmamos nuestra asistencia a los XV años de ${e.celebrant}.\nFamilia o persona encargada de mesa: ${name}\nNúmero de personas: ${count}`;
window.location.assign(`https://wa.me/${e.rsvp.whatsappNumber}?text=${encodeURIComponent(message)}`);
}
return <section id="confirmacion" className="whatsapp-confirmation ivory" aria-labelledby="confirmation-title"><Reveal><span className="section-index">07 / TE ESPERAMOS</span><h2 id="confirmation-title">Confirma que<br/><em>nos acompañas.</em></h2><p>Nos encantará compartir esta noche contigo.</p><form onSubmit={confirm}><label className="field" htmlFor="confirmation-family">Nombre de la familia o de la persona encargada de la mesa<input id="confirmation-family" name="family" required maxLength={120} pattern={String.raw`.*\S.*`} placeholder="Ej. Familia García o Ana López" autoComplete="name"/></label><label className="field" htmlFor="confirmation-people">Número de personas<input id="confirmation-people" name="people" type="number" min="1" step="1" required inputMode="numeric" placeholder="Incluyéndote a ti"/></label><button className="submit-button" type="submit">Confirmar por WhatsApp<ArrowUpRight size={18}/></button><p className="confirmation-note">Se abrirá WhatsApp con tus datos. Envía el mensaje para completar tu confirmación.</p></form></Reveal></section>
}
export default function Invitation(){const [opened,setOpened]=useState(false);const [playing,setPlaying]=useState(false);const audio=useRef<HTMLAudioElement>(null);const [coverMissing,setCoverMissing]=useState(false);const main=useRef<HTMLElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],['0%','100%']);
useEffect(()=>{document.body.style.overflow=opened?'':'hidden';return()=>{document.body.style.overflow=''}},[opened]);
// Opening must not depend on an animation completion callback.
async function playMusic(){const player=audio.current;if(!player)return;player.volume=.55;try{await player.play()}catch{setPlaying(false)}}
function open(){setOpened(true);void playMusic()}
function toggleMusic(){const player=audio.current;if(!player)return;if(player.paused)void playMusic();else player.pause()}
useEffect(()=>{if(opened)main.current?.focus({preventScroll:true})},[opened]);
return <><a href="#bienvenida" className="skip-link" tabIndex={opened?0:-1}>Ir al contenido</a><div className={opened?"intro intro-leaving":"intro"} inert={opened} aria-hidden={opened} role="dialog" aria-modal={!opened} aria-label="Abrir la invitación" lang="es"><div className="intro-panel left"/><div className="intro-panel right"/><div className="intro-seam"/><div className="intro-content"><span className="intro-top eyebrow">{e.eventType}</span><div className="intro-photo">
<div className="intro-photo-placeholder"><span className="intro-photo-mark">{e.initials}</span><span>Evelin &amp; Estrella</span></div>
{!coverMissing&&<Image src={e.cover.src} alt={e.cover.alt} fill unoptimized loading="eager" sizes="(max-width: 700px) 80vw, 420px" className="intro-photo-image" onError={()=>setCoverMissing(true)}/>}
</div><h2 className="intro-names"><span>Evelin</span><i>&amp;</i><span>Estrella</span></h2><p className="intro-date">{dateLabel({day:'2-digit',month:'2-digit',year:'numeric'}).replaceAll('/', ' · ')}</p><Rule/><p className="intro-title">{e.messages.intro}</p><button type="button" autoFocus onClick={open} className="open-button">Abrir invitación<ArrowUpRight size={16}/></button><span className="intro-foot">{e.eventName}</span></div></div>
<main ref={main} tabIndex={-1} inert={!opened} className={opened?"invitation invitation-opened":"invitation"}><motion.div className="reading-progress" style={{width:progress}}/><section className="hero dark">{e.hero.src&&<Image src={e.hero.src} alt={e.hero.alt} fill priority sizes="100vw" className="hero-image"/>}<div className="hero-grain"/><header className="hero-header"><span>{e.eventName}</span><span>{dateLabel({day:'2-digit',month:'2-digit',year:'2-digit'}).replaceAll('/', ' / ')}</span></header><div className="hero-frame"><div className="hero-content"><div className="hero-celebration"><Label>Nuestros</Label><span className="hero-xv">XV</span><Label>Años</Label></div><motion.h1 className="two-names" initial={{opacity:0,y:20}} animate={opened?{opacity:1,y:0}:{opacity:0,y:20}} transition={{duration:reduced?0:1.2}}>{e.celebrants.map((name,i)=><span key={i}>{i>0&&<i className="name-amp">&</i>}{name.name}</span>)}</motion.h1><p className="hero-date">{dateLabel({day:'2-digit',month:'long',year:'numeric'}).replaceAll(' de ', ' ').toUpperCase()}</p><Rule/><p className="hero-quote">{e.messages.hero}</p></div><div className="hero-bottom"><span>{e.eventType}</span><a href="#bienvenida" aria-label="Descubrir invitación"><ArrowDown size={20} strokeWidth={1}/></a><span>Una noche inolvidable</span></div></div><span className="hero-side">EL COMIENZO DE UN RECUERDO</span></section>
<section id="bienvenida" className="welcome ivory"><div className="section-top"><span className="section-index">01 / CON TODO EL CORAZÓN</span><span className="small-star">✧</span></div><Reveal><Label>Los momentos más bonitos se comparten</Label><h2 className="welcome-heading">{e.messages.welcomeTitle[0]}<br/><em>{e.messages.welcomeTitle[1]}</em></h2><p className="welcome-message">{e.messages.welcome}</p><Rule/><Label>Con el amor de nuestros padres</Label><div className="parents"><p>{e.parents[0]}</p><span>&</span><p>{e.parents[1]}</p></div></Reveal></section>
<section className="godparents ivory"><Reveal><Label>Con la bendición y compañía<br/>de nuestros padrinos</Label><div className="godparent-names">{e.godparents.map((name,i)=><motion.div key={name} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:reduced?0:i*.12,duration:reduced?0:.7}}><span className="name-number">0{i+1}</span><h3>{name}</h3></motion.div>)}</div></Reveal></section>
<section className="date-section ivory"><div className="date-aside"><span className="section-index">02 / RESERVA LA FECHA</span><Reveal><h2>Hay una fecha<br/>para <em>encontrarnos.</em></h2><p>{e.city}</p></Reveal></div><Reveal className="date-piece"><Label>{dateLabel({weekday:'long'})}</Label><span className="date-number">{dateLabel({day:'numeric'})}</span><div className="date-month"><span>{dateLabel({month:'long'})}</span><span>{dateLabel({year:'numeric'})}</span></div><a href="/api/calendar" className="text-link"><CalendarDays size={15}/>Agregar al calendario<ArrowUpRight size={16}/></a></Reveal></section><Countdown/>
<section id="lugares" className="ceremony ivory"><span className="section-index">03 / EL ENCUENTRO</span><Reveal><div className="ceremony-mark" aria-hidden="true">✧</div><Label>Ceremonia religiosa</Label><h2>{e.ceremony.title}<br/><em>{e.ceremony.subtitle}</em></h2><div className="venue-time">{e.ceremony.label}</div><p>{e.ceremony.description}</p>{e.ceremony.address&&<p>{e.ceremony.address}</p>}<VenueMap name={e.ceremony.name} embedUrl={e.ceremony.mapEmbedUrl}/><LocationLink url={e.ceremony.mapsUrl}>Ver ubicación</LocationLink></Reveal></section>
<section className="interlude"><motion.span initial={{scaleY:0}} whileInView={{scaleY:1}} viewport={{once:true}} transition={{duration:reduced?0:1.2}}/><Label>Después de la ceremonia...</Label></section>
<section className="reception dark"><div className="reception-orbit"/><Reveal><Label>Celebremos juntos</Label><h2>{e.reception.title}<br/><em>{e.reception.subtitle}</em></h2><Rule/><div className="venue-time">{e.reception.label}</div><p>La noche apenas comienza.</p>{e.reception.address&&<p>{e.reception.address}</p>}<VenueMap name={e.reception.name} embedUrl={e.reception.mapEmbedUrl}/><LocationLink url={e.reception.mapsUrl}>Cómo llegar</LocationLink></Reveal><span className="reception-caption">{e.eventName}</span></section>
<section className="itinerary ivory"><Reveal><Label>Cada momento, un recuerdo</Label><h2>Así será <em>la noche.</em></h2><Timeline/></Reveal></section>
{e.dressCode.visible&&<section id="vestimenta" className="dress-code ivory" aria-labelledby="dress-code-title"><Reveal><div className="dress-code-icons" aria-hidden="true"><svg viewBox="0 0 64 80" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="m22 9-12 6-6 43 10 2 4-29v40h28V31l4 29 10-2-6-43-12-6"/><path d="m22 9 10 9 10-9M22 9l10 43L42 9M21 13l-4 12 8 3-4 7 11 17 11-17-4-7 8-3-4-12M32 52v19M21 49h6m10 0h6"/><path d="m27 16 5 3 5-3v8l-5-3-5 3z"/><circle cx="36" cy="58" r="1"/><circle cx="36" cy="64" r="1"/></svg><span>✧</span><svg viewBox="0 0 64 80" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M23 8v10m18-10v10M23 8h-5l-2 16 9 10L8 71q24 9 48 0L39 34l9-10-2-16h-5M23 18q9 10 18 0M23 18l-7 6m25-6 7 6M25 34h14M24 38h16M27 42l-8 29m18-29 8 29M32 43v31"/></svg></div><Label>Código de vestimenta</Label><h2 id="dress-code-title"><em>{e.dressCode.text}</em></h2><Rule/><p>Te pedimos evitar los siguientes colores:</p><ul className="dress-colors">{[{name:'Beige',color:'#D8C6A6'},{name:'Rojo',color:'#C52D37'},{name:'Champagne',color:'#EEDDBB'},{name:'Dorado',color:'#BE963C'}].map(color=><li key={color.name}><span className="dress-color-dot" style={{backgroundColor:color.color}} aria-hidden="true"/><span>{color.name}</span></li>)}</ul></Reveal></section>}
{e.gallery.visible&&<section className="gallery ivory"><div className="gallery-heading"><span className="section-index">04 / FRAGMENTOS DE NUESTRA HISTORIA</span><Reveal><h2>Dos protagonistas.<br/><em>Una noche única.</em></h2><p className="gallery-intro">Así comienza un recuerdo para siempre.</p></Reveal></div><div className="portrait-gallery">{e.gallery.photos.map((photo,i)=><Reveal key={photo.src} className="portrait-card"><figure><div className="portrait-frame"><Image src={photo.src} alt={photo.alt} width={photo.width} height={photo.height} sizes="(max-width: 700px) 44vw, (max-width: 1200px) 42vw, 500px" loading="lazy"/></div><figcaption><span>{String(i+1).padStart(2,'0')}</span><span aria-hidden="true">✧</span></figcaption></figure></Reveal>)}</div><p className="gallery-foot">Dos historias. Un mismo recuerdo.</p></section>}
<section className="emotional dark"><Label>05 / LO QUE PERMANECE</Label><blockquote>{e.messages.emotional.map((line,i)=><Reveal key={line}><span className={i===2?'italic':''}>{line}</span></Reveal>)}</blockquote><Rule/></section>
<section id="regalos" className="gifts ivory" aria-labelledby="gifts-title"><Reveal><span className="section-index">06 / UN DETALLE CON CARIÑO</span><div className="gifts-envelope" aria-hidden="true"><Mail size={42} strokeWidth={1}/></div><Label>Tu presencia nos honra</Label><h2 id="gifts-title">El mejor regalo<br/><em>es tenerte aquí.</em></h2><p className="gifts-message">Si deseas tener un detalle con nosotras, agradeceremos tu cariño en una lluvia de sobres.</p><div className="gifts-card"><span aria-hidden="true">✧</span><h3>Lluvia de sobres</h3><p>Un regalo en efectivo dentro de un sobre,<br/>que puedes entregarnos el día de la celebración.</p><span className="gifts-thanks">Gracias por acompañarnos en este sueño.</span></div></Reveal></section>
<WhatsAppConfirmation/>
<footer className="closing dark"><div className="closing-mark">{e.initials}</div><Rule/><Label>{e.messages.closing}</Label><h2 className="closing-names">{e.celebrants.map((name,i)=><span key={i}>{i>0&&<i>&</i>}{name.name}</span>)}</h2><p className="closing-date">{dateLabel({day:'2-digit',month:'2-digit',year:'numeric'}).replaceAll('/', ' · ')}</p><p className="closing-last">Te esperamos.</p><div className="footer-bottom"><span>{e.eventName}</span><span>Con mucho cariño</span></div><p className="developer-credit">© 2026 · Desarrollado por <span>DanielDev</span></p></footer></main>
{e.music.src&&<audio ref={audio} src={e.music.src} loop preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setPlaying(false)}/>}
{opened&&e.music.src&&<button type="button" className="music-toggle" aria-label={playing?'Pausar música':'Reproducir música'} title={playing?'Pausar música':'Reproducir música'} aria-pressed={playing} onClick={toggleMusic}>{playing?<Volume2 size={21}/>:<VolumeX size={21}/>}</button>}
</>}
